version: 2.1

orbs:
  android: circleci/android@0.2.0
jobs:
  build:
    executor: android/android

    steps:
      - checkout

    build-debug-apk:
      steps:
        - run:
            command: ./gradlew build

    install-firebase:
      steps:
        - run:
            name: "Install Firebase CLI"
            command: |
              curl -sL firebase.tools | bash

    deploy-build:
      - run:
          command: firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk --app 1:688853618096:android:c544f2325370623bf29a75  --token 1//0gYok8JUUlpEaCgYIARAAGBASNwF-L9IrcwqV5iFkJZGNjCJpq9_A2bJsUP0Nwg-_8TS_uGMU0pHMnKjw5WFrSZj9K7YBlFn71sg --testers "ashishbitto07@gmail.com"
workflows:
  version: 1
  build-deploy:
    jobs:
      - build:
      - build-debug-apk:
        - requires:
            - build
          filters:
             branches:
               - only: master
      - install-firebase:
          filters:
            - only: master
      - deploy-build:
          requires:
            - install-firebase
            - build-bebug-apk
          filters:
            branches:
              only: master
              ignore: featire_firebase_otp
